---
title: "Iteration and list columns"
author: "Anna Ma"
date: "11/13/2021"
output: github_document
---

```{r}
library(tidyverse)

set.seed(1)
```

## Define Function 

```{r}
mean_and_sd = function(x) {
  
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) == 1) {
    stop("Cannot be computed for length 1 vectors")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)

  output_df = 
    tibble(mean = mean_x, 
       sd = sd_x)
  # or use list(mean = mean_x, sd = sd_x)
  return(output_df)
}
```

## Lists

```{r}
l = 
  list(
    vec_numeric = 5:8,
    vec_logical = c(TRUE, FALSE),
    summary = summary(rnorm(1000, mean = 5, sd = 3))
)

# 3 ways to access the third element of this list:

l[[3]]

l[["summary"]]

l$summary

```

## List of normals

```{r}
list_norms = 
  list(
    a = rnorm(50, mean = 2, sd = 1),
    b = rnorm(50, mean = 5, sd = 3),
    c = rnorm(50, mean = 20, sd = 1.2),
    d = rnorm(50, mean = -12, sd = 0.5)
  )
```

## Use function on list 

```{r}
mean_and_sd(list_norms[[1]])
```

